oscontainer: Only use buildah to work around nested `podman push` bug
I'm seeing this in my f34 toolbox trying to use `upload-oscontainer`:

```
+ podman --root=./tmp/containers-storage --storage-driver vfs push --tls-verify --authfile=/var/home/walters/.docker/config.json registry.ci.openshift.org/coreos/walters-rhcos-47:47.84.202109021332-0 --digestfile=tmp/oscontainer-digest
Error: failed to open 2048 locks in /libpod_lock: permission denied
```

I didn't dig deep into it; tried adding `--runroot` but that
didn't help.  Anyways, since `buildah` is I think better
tested for this purpose (nested container builds) let's use just
it instead of both `buildah` and `podman`.

This fixes the above bug.