cosalib/container_manifest.py: cleanup manifest before create/push
If a manifest previously exists then let's try to clean it up before
continuing. We saw this in the pipeline where one run failed in the
middle and then a later run failed because the manifest existed:

```
2024-11-19 14:29:26,184 INFO - Running command: ['podman', 'manifest', 'create', 'quay.io/coreos-assembler/coreos-assembler:main']
Error: creating manifest: image name "quay.io/coreos-assembler/coreos-assembler:main" is already associated with image "ffbb463bfb0e3bb0fb4c42856d2dca0ff985d1dd5d7b34f1b3ae0277287ad83d": that name is already in use
```