WIP: Introduce meta/resource-version
Split out of discussions in https://github.com/coreos/coreos-assembler/pull/1657

I tested that running in the same cosa workdir in two separate
shells, `cosa buildextend-aws` and `cosa buildextend-gcp`

fails with:

```
[INFO]: Calculating metadata for fedora-coreos-32.20200805.dev.0-gcp.x86_64.tar.gz
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-buildextend-gcp", line 103, in <module>
    build.build_artifacts()
  File "/usr/lib/coreos-assembler/cosalib/build.py", line 382, in build_artifacts
    self._build_artifacts(*args, **kwargs)
  File "/usr/lib/coreos-assembler/cosalib/qemuvariants.py", line 309, in _build_artifacts
    self.meta_write()
  File "/usr/lib/coreos-assembler/cosalib/build.py", line 369, in meta_write
    self.meta.write()
  File "/usr/lib/coreos-assembler/cosalib/meta.py", line 85, in write
    raise Exception(f"resource-version conflict updating {self._meta_path}, expected {newver}, found {curver}")
Exception: resource-version conflict updating /var/srv/walters/builds/fcos/builds/32.20200805.dev.0/x86_64/meta.json, expected 2, found 3
```