build.sh: freeze grub2 to fix PXE + UEFI tests
The `pxe-install` build started failing after grub2-2.06-67.fc37 entered
cosa:

    Loading kernel
    error: ../../grub-core/fs/fshelp.c:257:file
    `/rhcos-413.86.202211301346-0-live-kernel-x86_64' not found.

Possibly the same root cause as
https://github.com/coreos/fedora-coreos-tracker/issues/1352.

Freeze on the previous version for now until we figure this out.

(cherry picked from commit 89f3070c9d1fcbe3400eeb074826d6c12155e111)

jlebon: `rhcos-4.10` is on f35, so I froze on grub2-2.06-11.fc35
        instead, which was the grub2 version we were using before
        https://bodhi.fedoraproject.org/updates/FEDORA-2022-7ce9378e90
        was pushed.