cmd-build: drop --previous-build-manifest= when generating container
Since we are moving to building with the container workflow [1] and
there is no equivalent functionality there [2] (for now), let's drop
this logic from cmd-build.

If we leave this logic enabled local developers who are mixing the
`COSA_BUILD_WITH_BUILDAH=1 cosa build` and classic `cosa build`
workflows will hit an error.

```
Generating container image
error: Encapsulating: Building oci: Missing ostree.components on prior build
failed to execute cmd-build: exit status 1
```

This was documented in [3].

[1] https://github.com/coreos/coreos-assembler/commit/bf41ab7422736f78b05c1f0f12bca01a16d28514
[2] https://github.com/coreos/rpm-ostree/issues/5459
[3] https://github.com/coreos/coreos-assembler/issues/4250