kola/tests: iso/iscsi: adjust volume mount for boot.ipxe
Using /srv here in the past was special. In some cases the COSA
workdir is `/srv` and in others (like in prow) it's some directory
in /tmp/ (like /tmp/cosa), which somehow made the test pass in
jenkins/local but fail in prow.

To reproduce the issue locally you could try to change it to
`Volume=/srv/boot.ipxe:/mnt/boot.ipxe` to observe the same
failure as viewed in prow, which is something like:

```
open `/var/cosaroot/srv/boot.ipxe`: No such file or directory
Error: crun: open `/var/cosaroot/srv/boot.ipxe`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

in the `nested_vm_console.txt`.

The fix here is to just use a directory we know will be writable.
Since we use /root as our workdir here let's just put it there.