cosalib: fix init_build_meta_json for multi-arch
If we are starting out a brand new stream and the x86_64 build
has completed, but there was no build yet for $arch then the detected
previous buildid:

```
previous_buildid = parent_build or self.get_latest()
```

Will just be the build ID of the x86_64 build from `get_latest()`,
but this code tries to open a meta.json for it from $arch, which
won't exist. Here's the error we see:

```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/usr/lib/coreos-assembler/cosalib/builds.py", line 134, in init_build_meta_json
    with open(metapath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/srv/builds/36.20220714.dev.0/aarch64/meta.json'
error: failed to execute cmd-build: exit status 1
```

This should fix that error by verifying the detected buildid actually
has a build for that architecture before continuing.

(cherry picked from commit 786e87b59d7bbc67b5f36a3fd56fb9e3e75912f3)